server:
  port: 9092
  
debug: true
  
spring:
  h2:    console:      enabled: true
  datasource:    url: jdbc:h2:mem:customerdb
    driver-class-name: org.h2.Driver
    username: admin
    password: admin
    
  jpa:    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:      ddl-auto: create-drop
    show-sql: true
 